tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^register_profile/$', views.register_profile,
        name='register_profile'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^view_profiles/$', views.view_profiles, name='view_profiles'),
    url(r'^view_profiles/(?P<profile_name>\w+)/$', views.profile_detail, name='profile_detail'),
]

### old urls
#    url(r'^login/$', views.user_login, name='login'),
#    url(r'^logout/$', views.user_logout, name='logout'),
#    url(r'^register/$', views.register, name='register'),

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from rango import views

# Create a new class that redirects the user to the index page,
# if successful at registration
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return 'rango:register_profile'

# register pattern must be before accounts so it'll trigger first
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/register/$',
        MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone

### MODEL ORDER 
# constants
# fields
# custom manager
# meta
# def __str__
# other special methods
# def clean
# def save
# def get_absolute_url
# other methods

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode() method to return out something meaningful!
    def __str__(self):
        return self.user.username

class Category(models.Model):
    LEN_NAME = 128
    name = models.CharField(max_length=LEN_NAME, unique=True)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0: self.views = 0
        if self.likes < 0: self.likes = 0
        super(Category, self).save(*args, **kwargs)

class Page(models.Model):
    LEN_TITLE = 128
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=LEN_TITLE)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(null=True)
    first_visit = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        now = timezone.now()
        if self.last_visit and self.last_visit > now:
            self.last_visit = now
        if self.first_visit and self.first_visit > now:
            self.first_visit = now
        super(Page, self).save(*args, **kwargs)

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import UserProfile, Category, Page

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email',)

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.LEN_NAME,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.LEN_TITLE,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exlucde the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not (url.startswith('http://') or url.startswith('https://')):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

tango_with_django_project/rango/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate
from django.utils import timezone
from rango.models import Category, Page, User, UserProfile
from rango.forms import CategoryForm, PageForm, UserProfileForm, UserUpdateForm
from rango.bing_search import run_query
from rango.forms import UserForm, UserProfileForm
#from django.contrib.auth import authenticate, login, logout

def index(request):
    # Cookie test
    #request.session.set_test_cookie()

    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary
    # that will be passed to the template engine.

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    ### switching to server side sessions
    # obtain our Response object early so we can add cookie information
    #response = render(request, 'rango/index.html', context_dict)

    # call function to handle the cookies
    # function modifies response cookie settings
    #visitor_cookie_handler(request, response)

    ### server side session cookie handling
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)

    # return response back to the user, updating any cookies that need changed
    return response

    # pre-cookie implementation
    # Render the response and send it back!
    #return render(request, 'rango/index.html', context_dict)

    ### old test version
    ## construct a dictionary to pass to the template engine as its context
    ## key "boldmessage" is same as {{ boldmessage }} in template
    #context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}

    ## return rendered response to send to client
    ## render shortcut function to make response construction easy
    ## first param is template we wish to use
    #return render(request, 'rango/index.html', context=context_dict)

# server side cookie helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')

    # if it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        # update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    # update/set the visits cookie
    request.session['visits'] = visits

### visitor cookie helper function
### pre server-side version
#def visitor_cookie_handler(request, response):
#    # get the number of visits to the site.
#    # we use the COOKIES.get() function to obtain the visits cookie.
#    # if the cookie exists, the value returned is casted to an integer
#    # if the cookie doesn't exist, then the default value of 1 is used
#    visits = int(request.COOKIES.get('visits', '1'))
#
#    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
#    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
#                                        '%Y-%m-%d %H:%M:%S')
#
#    # if it's been more than a day since the last visit...
#    if (datetime.now() - last_visit_time).days > 0:
#        visits += 1
#        # update the last visit cookie now that we've updated the count
#        response.set_cookie('last_visit', str(datetime.now()))
#    else:
#        # set the last visit cookie; stays the same since same day
#        response.set_cookie('last_visit', last_visit_cookie)
#
#    # update/set the visits cookie
#    response.set_cookie('visits', visits)

def about(request):
    # test cookie
    #if request.session.test_cookie_worked():
    #    print("TEST COOKIE WORKED!")
    #    request.session.delete_test_cookie()
    #else:
    #    print("NO COOKIES :(")

    return render(request, 'rango/about.html', {'visits': request.session.get('visits', None)})

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category).order_by('-views')

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template wil display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

    ### Search function
    context_dict['query'] = category.name
    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)
            context_dict['result_list'] = result_list
            context_dict['query'] = query

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            #form.save(commit=True)
            cat = form.save(commit=True)
            # prints category to server console
            print(cat, cat.slug)
            # Now that the category is saved
            # We could give a confirmation message
            # But since the most recent category added is on the index page
            # Then we can just direct the user back to the index page.
            #return index(request)
            return redirect('rango:index')
        else:
            # The supplied form contained errors -
            # Just print them to the terminal
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                print("Page created:", page)
                return redirect('rango:show_category', category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

### UserForm, UserProfileForm
#def register(request):
#    # A boolean value for telling the template
#    # whether the registration was successful.
#    # Set to False initially. Code changes value to
#    # True when registration succeeds.
#    registered = False
#
#    # If it's a HTTP POST, we're interested in processing form data
#    if request.method == 'POST':
#        # Attempt to grab information from the raw form information.
#        # Note that we make use of both UserForm and UserProfileForm.
#        user_form = UserForm(data=request.POST)
#        profile_form = UserProfileForm(data=request.POST)
#
#        # If the two forms are valid...
#        if user_form.is_valid() and profile_form.is_valid():
#            # Save the user's form data to the database.
#            user = user_form.save()
#
#            # Now we hash the password with the set_password method.
#            # Once hashed, we can update the user object.
#            user.set_password(user.password)
#            user.save()
#
#            # Now sort out the UserProfile instance.
#            # Since we need to set the user attribute ourselves,
#            # we set commit=False. This delays saving the model
#            # until we're ready to avoid integrity problems.
#            profile = profile_form.save(commit=False)
#            profile.user = user
#
#            # Did the user provide a profile picture?

tango_with_django_project/rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    <h1>{% block title_block %}About Rango{% endblock %}</h1>
    <div>
        <img src="{% static 'images/blep.jpg' %}" alt="Blep." width="30%" />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Cat." width="50%" />
        <p>This tutorial has been put together by FeebleOldMan.</p>
        {% if user.is_authenticated %}
        <p>visits: {{ visits }}</p>
        {% endif %}
        {% comment "pull local cookie data" %}
        <p>visits: {{ request.COOKIES.visits }}</p>
        {% endcomment %}
    </div>
    <div>
        <button class="btn btn-primary"
            onClick="alert('You clicked the button that runs JavaSCript.');">
            Click Me - I run Javascript
        </button>
        <button class="btn btn-primary" id="about-btn">
            Click Me - I run jQuery
        </button>
        <p>This is an example</p>
        <p>This is another example</p>
    </div>
    <div id="msg">Hello - I'm here for a jQuery example too</div>
{% endblock %}

tango_with_django_project/rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}

{% block title_block %}Add Category{% endblock %}

{% block body_block %}
    <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
        <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {{ form|as_bootstrap }}
        {% comment 'before bootstrap' %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
        {% endfor %}
        {% endcomment %}
        <br />
        <button class="btn btn-primary" type="submit" name="submit">
            Add Category
        </button>
    </form>
{% endblock %}

tango_with_django_project/rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title_block %}Add Page{% endblock %}

{% block body_block %}
    {% if category %}
    <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        <h2 class="form-signin-heading">Add a Page to
            <a href="{% url 'rango:show_category' category.slug %}">
                {{ category.name }}
            </a>
        </h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
        {% endfor %}
        <br />
        <button class="btn btn-primary" type="submit" name="submit">
            Add Page
        </button>
    </form>
    {% else %}
    <p>This category does not exist.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/base.html
<!DOCTYPE html>
{% load static rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>{% block title_block %}How to Tango with Django!{% endblock %} | Rango</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet" />

  </head>

  <body>

    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>
      <div id="navbar">
        <nav class="nav navbar-nav pull-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
          <!--<a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>-->
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add New Category</a>
          <a class="nav-item nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a>
          <a class="nav-item nav-link" href="{% url 'rango:profile' %}">Edit Profile</a>
          <a class="nav-item nav-link" href="{% url 'rango:view_profiles' %}">View Profiles</a>
          <a class="nav-item nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
          <a class="nav-item nav-link" href="{% url 'auth_logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'registration_register' %}">Sign Up</a>
          {% endif %}
        </nav>
        <!--
        <form class="pull-xs-right">
          <input type="text" class="form-control" placeholder="Search...">
        </form>
        -->
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <input class="input-medium search-query" type="text" name="suggestion" value="" id="suggestion" placeholder="Search categories..." />
              <hr />
              <div id="cats">
                {% block side_block %}
                {% get_category_list category %}
                {% endblock %}
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% block body_block %}
        {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <!-- using bootstrap version instead
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    -->
    <script src="{% static "js/rango-jquery.js" %}"></script>
    <!-- obtain django ajax variables -->
    <script>
        const like_url = "{% url 'rango:like_category' %}"
        const suggest_url = "{% url 'rango:suggest_category' %}"
        const auto_add_url = "{% url 'rango:auto_add_page' %}"
    </script>
    <script src="{% static "js/rango-ajax.js" %}"></script>
  </body>
</html>

tango_with_django_project/rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
    {% if category %}
    <h1>{% block title_block %}{{ category.name }}{% endblock %}</h1>
    <div>
        <strong id="like_count">{{ category.likes }}</strong> like{{ category.likes|pluralize }}
        {% if user.is_authenticated %}
        <button class="btn btn-primary btn-sm" id="likes" type="button" data-catid="{{ category.id }}">Like</button>
        {% endif %}
    </div>
    <div id="page">
        <ul>
            {% for page in pages %}
            <li>
                <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                ({{ page.views }} view{{ page.views | pluralize }})
                | {{ page.last_visit|default:"Unvisited" }}
            </li>
            {% empty %}
            <strong>No pages currently in category.</strong>
            {% endfor %}
        </ul>
    </div>
        {% comment "replacing with empty block" %}
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}
        {% endcomment %}
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    {% if user.is_authenticated %}
        <hr />
        <form class="form-inline" id="user_form"
            method="post" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50"
                    name="query" value="{{ query }}" id="query" autofocus />
            </div>
            <button class="btn btn-primary" type="submit" name="submit"
                value="Search">Search</button>
        </form>

        {% if result_list %}
        <div>
            <h3>Results</h3>
            <!-- Display search results in an ordered list -->
            <div class="list-group">
                {% for result in result_list %}
                <div class="list-group-item row">
                    <h4 class="list-group-item-heading col-sm-9">
                        <a href="{{ result.link }}">{{ result.title }}</a>
                    </h4>
                    <div class="col-sm-3">
                    {% if user.is_authenticated %}
                    <button data-catid="{{ category.id }}" data-title="{{ result.title }}" data-url="{{ result.link }}" data-csrf="{% csrf_token %}"class="rango-add btn btn-info btn-sm pull-right" type="button">Add</button>
                    {% endif %}
                </div>
                    <p class="list-group-item-text col-sm-12">{{ result.summary }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    {% endif %}

{% endblock %}

tango_with_django_project/rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    howdy {{ user.username|default:"partner" }}!
    {% comment "using default instead of if" %}
    <p>Visits: {{ visits }}</p>
    {% if user.is_authenticated %}
    howdy {{ user.username }}!<br />
    {% else %}
    hey there partner!<br />
    {% endif %}
    <!--<strong>{{ boldmessage }}</strong></br />-->
    {% endcomment %}
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item">
                    <a href="{% url 'rango:show_category' category.slug %}">
                        {{ category.name }}
                        <button class="btn btn-sm btn-info">{{ category.likes }}</button>
                    </a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>There are no categories present.</strong>
            {% endif %}
        </p>
    </div>

    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item">
                <a href="{{ page.url }}">{{ page.title }}</a>
                <button class="btn btn-sm btn-info">{{ page.views }}</button>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>There are no pages present.</strong>
            {% endif %}
        </p>
    </div>

    <div>
        <img src="{% static "images/rango.jpg" %}" alt="Rango." />
    </div>
</div>
{% endblock %}

tango_with_django_project/rango/templates/rango/pages.html
<ul>
    {% for page in pages %}
    <li>
        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
        ({{ page.views }} view{{ page.views | pluralize }})
    </li>
    {% empty %}
    <strong>No pages currently in category.</strong>
    {% endfor %}
</ul>

tango_with_django_project/rango/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block body_block %}
    <h1>{% block title_block %}Restricted{% endblock %}</h1>
    Top secret<br />
    Aliens<br />
    The X-Files<br />
{% endblock %}

tango_with_django_project/rango/templates/rango/search.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
<div>
    <h1>{% block title_block %}Search{% endblock %} with Rango</h1>
    <br />
    <form class="form-inline" id="user_form"
        method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50"
                name="query" value="{{ query }}" id="query" autofocus />
        </div>
        <button class="btn btn-primary" type="submit" name="submit"
            value="Search">Search</button>
    </form>

    <div>
        {% if result_list %}
        <h3>Results</h3>
        <!-- Display search results in an ordered list -->
        <div class="list-group">
            {% for result in result_list %}
            <div class="list-group-item">
                <h4 class="list-group-item-heading">
                    <a href="{{ result.link }}">{{ result.title }}</a>
                </h4>
                <p class="list-group-item-text">{{ result.summary }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}